language: php
php:
  - 7.0
  - 7.1
  - 7.2
env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""
before_script:
  - composer update $PREFER_LOWEST
script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: ./vendor/bin/coveralls -v
